CREATE DATABASE IF NOT EXISTS HDS_DEMO;

CREATE TABLE IF NOT EXISTS HDS_DEMO.EMPLOYEES (
     EID INT, 
     NAME STRING,
     SALARY STRING, 
     DESIGNATION STRING
)
COMMENT 'Employee details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS HDS_DEMO.DEPARTMENT (
     DEPT_ID INT,
     DEPT_NAME STRING,
     STRENGTH INT,
     MANAGER STRING
)
COMMENT 'Department details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

--DROP DATABASE IF EXISTS HDC_DEMO CASCADE;