CREATE DATABASE IF NOT EXISTS HDC_DEMO;

CREATE TABLE IF NOT EXISTS HDC_DEMO.EMPLOYEES (
     EID INT, 
     NAME STRING,
     SALARY STRING, 
     DESIGNATION STRING
)
COMMENT 'Employee details'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

DROP DATABASE IF EXISTS HDC_DEMO CASCADE;