---
sources:
  oracle:
    class_name: OracleCrawler
    dao: Oracle
  netezza:
    class_name: NetezzaCrawler
    dao: Netezza
  hive:
    class_name: HiveCrawler
    dao: Hive

destinations:
  snowflake:
    class_name: SnowflakeCreator
    dao: SnowflakeDAO

mappers:
  oracle:
    snowflake: OracleToSnowflake
  netezza:
    snowflake: NetezzaToSnowflake
  hive:
    snowflake: HiveToSnowflake

connection_profiles:
  oracle: oracle_jdbc_with_service_name
  netezza: netezza_jdbc
  snowflake: snowflake_knerrir_writer
  hive: hive_test_profile
...