---
sources:
  oracle:
    type: OracleCrawler
    conf:
      name: oracle_xepdb1_jdbc
      type: Oracle
  netezza:
    type: NetezzaCrawler
    conf:
      name: netezza_jdbc
      type: Netezza
  hive:
    type: HiveCrawler
    conf:
      name: hive_metastore_knerrir_dataproc
      type: Hive

destinations:
  snowflake:
    type: SnowflakeCreator
    conf:
      name: snowflake_knerrir_writer
      type: SnowflakeDAO

mappers:
  oracle:
    snowflake: OracleToSnowflake
  netezza:
    snowflake: NetezzaToSnowflake
  hive:
    snowflake: HiveToSnowflake
...
