# Copyright © 2020 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: 1
formatters:
  info_frmt:
    format: '[%(asctime)s]: [%(levelname)s]: [%(name)s.%(funcName)s(...)]: [message = "%(message)s"]'
  debug_frmt:
    format: '[%(asctime)s]: [%(levelname)s]: [%(module)s.%(lineno)d]: [%(name)s.%(funcName)s(...)]: [message = "%(message)s"]'
  # json:
  #   format: '%(asctime)s %(name)s.%(funcName)s %(levelname)s %(message)s'
  #   class: pythonjsonlogger.jsonlogger.JsonFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: info_frmt
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: info_frmt
    level: DEBUG
    filename: hdc.log
    maxBytes: 1048576
    backupCount: 20
loggers:
  Cataloger:
    level: INFO
    handlers: [ console ]
  AssetMapper:
    level: INFO
    handlers: [ console ]
  Crawler:
    level: INFO
    handlers: [ console ]
  Creator:
    level: INFO
    handlers: [ console ]
  Mapper:
    level: INFO
    handlers: [ console ]
  DAO:
    level: DEBUG
    handlers: [ console ]